apiVersion: apps/v1
kind: Deployment
metadata:
  name: goweb-deployment
  labels:
    app: goweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goweb
  template:
    metadata:
      labels:
        app: goweb
    spec:
      containers:
      - name: goweb
        image: bilbothegreedy/goweb_image:latest
        ports:
        - containerPort: 80