version: "3.3"

networks:
  portainer:
    driver: overlay
services:
  portainer:
    image: portainer/portainer
    command: --no-auth --host=unix:///var/run/docker.sock
    ports:
      - 9001:9000
    networks:
      - portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      placement:
        constraints:
         - node.role == manager